platform :ios, '11.0'

flutter_application_path = '../flutter_app/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Demo' do
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
end
