# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Kingfisher', '~> 4.10.1'

flutter_application_path = '../flutter_module'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

  # Pods for FlutterDemo

end
