name: veggieseasons
description: An iOS app that shows the fruits and veggies currently in season.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.15.7
  scoped_model: ^1.0.1
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/images/apple.jpg
    - assets/images/artichoke.jpg
    - assets/images/asparagus.jpg
    - assets/images/avocado.jpg
    - assets/images/blackberry.jpg
    - assets/images/canteloupe.jpg
    - assets/images/cauliflower.jpg
    - assets/images/endive.jpg
    - assets/images/fig.jpg
    - assets/images/grape.jpg
    - assets/images/green_bell_pepper.jpg
    - assets/images/habanero.jpg
    - assets/images/kale.jpg
    - assets/images/kiwi.jpg
    - assets/images/lemon.jpg
    - assets/images/lime.jpg
    - assets/images/mango.jpg
    - assets/images/mushroom.jpg
    - assets/images/nectarine.jpg
    - assets/images/persimmon.jpg
    - assets/images/plum.jpg
    - assets/images/potato.jpg
    - assets/images/radicchio.jpg
    - assets/images/radish.jpg
    - assets/images/squash.jpg
    - assets/images/strawberry.jpg
    - assets/images/tangelo.jpg
    - assets/images/tomato.jpg
    - assets/images/watermelon.jpg
    - assets/images/orange_bell_pepper.jpg

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
          weight: 400
